### PR TITLE
add module for join.me Public API

### PR DESCRIPTION
**Pull request by suttonj**
join.me (an online collaboration tool) is opening up an API for developers to integrate join.me's workflow into their own apps. We'd like to use hello.js to facilitate client-side OAuth2 authentication. 

I think I've included all the necessary items for a pull request, with the exception of not being able to test a demo originating on the hello.js homepage (adodson.com/hello.js). I did provide a client ID key to use for the demo, and you are free to register one yourself at https://developer.join.me . 

Let me know if you have any concerns!

### CODE REVIEW

**Comment by MrSwitch** [comment]
Probably better to run jscs locally, it can be quicker to debug.

**Comment by MrSwitch** [comment]
Nice PR!

**Comment by MrSwitch** [comment]
@suttonj if you can include a joinme icon in https://github.com/samcollins/css-social-buttons that would tick the final box.

**Comment by suttonj** [comment]
Thanks! I'll get a joinme icon to that repo as soon as I can.

**Comment by suttonj** [comment]
@MrSwitch join.me icon is now in the css-social-buttons project (https://github.com/samcollins/css-social-buttons/pull/89) fyi, sorry for the delay

**Comment by MrSwitch** [comment]
I've temporarily included it in dist/hello.all*.js as of v1.8.4. However that said, i will likely slice the bundled package and remove the outliers like joinme, soundcloud etc, which judging by the community get very little mention, and i doubt are being used.
Thanks

**Pull request merged**
