### PR TITLE
Added unit tests for formatting of JSON feeds for different API/network requests

### PR DESCRIPTION
**Pull request by WebSeed**
Hi @MrSwitch, please take a look at the diff - I've begun adding unit tests for different networks based on anonymised captures are real API calls. I've started with ```/me``` API calls and added Instagram, Facebook and Google (Plus).

To date there don't appear to be any tests which cover transformations of the data when passed through ```wrap```. The reason I want to do this is because going forward I'd like to extend the ```/me/photos``` and ```/me/album(s)``` response, but would like unit tests to cover changes.

If this seems okay, I'll add tests for other networks (it won't be exhaustive as this would take a long time).

### CODE REVIEW

**Comment by MrSwitch** [comment]
This is awesome, and much needed in the project. Thanks for starting this off - lots more data mocks to go.

**Comment by MrSwitch** [comment]
What are you using `utils.forEach` for?

**Comment by WebSeed** [comment]
I'm only using it in the tests at the moment ('''tests/specs/unit/core/modules.js'''). I like a functional approach to iterating over collections e.g map, filter, reduce. Understand this might be a personal preference thing, quite happy to remove from utils and replace with a '''for''' loop if you like.

**Comment by MrSwitch** [comment]
Yep please remove it, or put it outside of the `src/` directory

**Comment by WebSeed** [comment]
Okay removed. Note it was put here with a view to perhaps using it elsewhere (in data transformation) but not really necessary.

**Comment by MrSwitch** [comment]
Yep affirmative (another PR perhaps) :)

**Comment by WebSeed** [comment]
Hi @MrSwitch. I've added a load of ```/me``` API stubs. Outstanding is ```flickr``` (received a 502 Bad Gateway) error and ```tumblr``` (not shown on the hello.js website currently). Would you consider merging this PR and I'll open up a new one soon with ```/me/photos``` and ```/me/album(s)``` stubs?

**Comment by MrSwitch** [comment]
Looks good, i replaced `describe.only` i dont think you had meant to leave that in.

**Comment by WebSeed** [comment]
Oops yes, thanks.

**Pull request merged**
