### PR TITLE
Fix README.md

### PR DESCRIPTION
**Pull request by jestersunborn**

### CODE REVIEW

**Comment by MrSwitch** [comment]
It's used to create the demo on https://adodson.com/hello.js/

Is this otherwise causing an issue for you?

**Comment by jestersunborn** [comment]
Oh, ok. I saw this and thought what this is a problem.
image

**Comment by jestersunborn** [comment]
Feel free to close this PR)🖖🏼

**Comment by MrSwitch** [comment]
Oh ok, i see what you mean the issue is on https://github.com/MrSwitch/hello.js, interesting.
I guess i should externalize this script

**Pull request closed without merging**
