### PR TITLE
Upgrade to facebook graph v2.9

### PR DESCRIPTION
**Pull request by gtothesquare**
Solves issue #493

### CODE REVIEW

**Comment by raulroyer** [comment]
I still see a reference to api v2.3 on the param 'next' from the popup dialog for login. You can see it in your own demo for [hellologin](https://adodson.com/hello.js/#hellologin).

**Comment by gtothesquare** [comment]
@raulroyer I don't know what you mean by "on the param 'next'"

**Comment by raulroyer** [comment]
@gtothesquare check the part of the url at the right of the image, it has a reference to api v2.3.
fb

**Comment by MrSwitch** [comment]
What's the version of HelloJS?

Also, just put this into a packaged release https://github.com/MrSwitch/hello.js/releases/tag/v1.15.0

**Comment by raulroyer** [comment]
@MrSwitch the version is v1.14.1

**Comment by gtothesquare** [comment]
@raulroyer @MrSwitch 
I have the 1.14.1 also. 
It redirects automatically to v2.3 which is the oldest supported version. This is stated in the docs:

> For APIs, once a version is no longer usable, any calls made to it will be defaulted to the next oldest usable version...

https://developers.facebook.com/docs/apps/versions

So one way to go is to do this
https://github.com/MrSwitch/hello.js/pull/498

However, I will say adding a config were the user of this lib can state which version they want is the way to go, so we avoid doing PRs everytime there is facebook api release.

**Pull request merged**
