### PR TITLE
Add commonjs module declaration

### PR DESCRIPTION
**Pull request by nnarhinen**
This is needed so that hello.js can be used directly from npm and
browserify.

### CODE REVIEW

**Comment by RangerMauve** [comment]
Would it make sense to maybe base the build on CommonJS/Browserify? Then you might have the potential to use the api wrappers with existing tokens on the server-side.

**Comment by MrSwitch** [comment]
@RangerMauve it probably would. Its just time and complexity managing something which could work on very distinct environments.

I created [dear](https://github.com/MrSwitch/dear) to use the hellojs on the server with existing tokens. But i'd like to expand this out at somepoint and trigger login and manage sessions.

**Comment by RangerMauve** [comment]
Oh neat, I hadn't noticed that that existed. I notice that your actual API definitions are still in HelloJS, maybe it'd make sense to put that part into its own module and have Hello.js be the client-side wrapper over everything and dear be the server-side?

**Comment by MrSwitch** [comment]
Hmmm yeah may do. I'm a little reluctant add a precompile step to the front end build. I feel it adds complexity and discourages participation in the project. But I may concede in the future if managing `dear` and `hellojs` side by side becomes difficult.

**Comment by RangerMauve** [comment]
Doesn't it already rely on Grunt?

**Comment by MrSwitch** [comment]
For bundling the modules, yes. For developing in a browser, no. See http://adodson.com/hello.js/demos/twitter.html which points to files straight from src/ directory

**Pull request merged**
