### PR TITLE
flickr was not supporting the me/album directive. This fixes that.

### PR DESCRIPTION
**Pull request by crowmagnumb**

### CODE REVIEW

**Comment by MrSwitch** [comment]
The js style settings require single quotes around strings.  Otherwise great!

**Comment by crowmagnumb** [comment]
Oh, crap. I realized that you used single quotes at the last minute so I went and made a quick edit before doing the PR and actually broke it because I only changed two of the four double quotes to single. Let me fix that and redo the PR.

**Comment by crowmagnumb** [comment]
Passed the params in a standard way now too.

**Comment by MrSwitch** [comment]
You have an "illegal space after key" see travis report on how to fix this.

**Comment by crowmagnumb** [comment]
OK, this time I also ran ```npm test``` myself now that I figured out how that works and this time it passed. Sorry for that.

**Comment by MrSwitch** [comment]
Great thanks

**Pull request merged**
