### PR TITLE
[DO NOT MERGE] Experiment: refactor functionality into separate files

### PR DESCRIPTION
**Pull request by WebSeed**
Hey @MrSwitch,

https://github.com/MrSwitch/hello.js/blob/master/src/hello.js has grown quite large (2639 lines). It seems like there would be a natural way to split this into separate files. Something like:

```
utils.js (in the future perhaps /utils/extend, /utils/qs etc.)
core.js (depends on utils.js includes settings, services, init, login, logout, getAuthResponse, events)
api.js (depends on utils.js)
```

The idea would be that the current `hello.js` would be compiled from the above. We could keep dependency management really simple (`(function (a, b, ...) { ... } (dep1, dep2, ...))`, or consider perhaps CommonJS and integrate Browserify into the Grunt / NPM build chain. Is this something you'd be interested in before I go any further with this branch?

### CODE REVIEW

**Comment by MrSwitch** [comment]
@WebSeed i totally do want to do this, incase you haven't seen i did spin off another project [dear](https://github.com/MrSwitch/dear) to recreate HelloJS in the commonjs environment. Prior to that i restructured the project with [AMD](https://github.com/MrSwitch/hello.js/tree/feature-amd/src).

AMD (or perhaps just RequireJS) was a pain. And i've become rather attached to the zero build process.

Harmony module loading when it lands in a browser will totally let us have cake and eat it. 

The benefits to breaking it up would be huge. The code would be much cleaner and large functions could be broken up too. But as i found with the AMD branch it was hard to maintain it, since any changes within master would be difficult to then merge in. So it really has to be worth it. Not sure it is worth the time at the moment.

**Comment by WebSeed** [comment]
> incase you haven't seen i did spin off another project dear to recreate HelloJS in the commonjs environment. Prior to that i restructured the project with AMD.

No I hadn't seen that before - looks good (exactly the kind of thing I was thinking of!). I understand the appeal of zero build process and agree that AMD adds quite a lot of noise the the code. However, as a contributor I find it quite hard to make sense of such a large block of code at the moment.

I wonder if there is a sweet spot (for now, until ES6 module loading) which doesn't require any particular dependency management but uses `shunt:build` (just extending what you do currently) and combining this with a watch task to rebuild `dist/hello.js` E.g. from this:

```js
  shunt: {
    docs: {
      'README.md': './index.html'
    },
    build: {
      'dist/hello.js': [
        'src/hello.polyfill.js',
        'src/hello.js',
        'src/hello.legacy.js',
        'src/hello.amd.js',
        'src/hello.commonjs.js'
      }
    }
  }
}

To (something like) this:

```js
  shunt: {
    docs: {
      'README.md': './index.html'
    },
    build: {
      'dist/hello.js': [
        'src/hello.polyfill.js',
        'src/hello.Promises', /* NEW */
        'src/hello.utils.js', /* NEW */
        'src/hello.core.js',  /* NEW */
        'src/hello.api.js',   /* NEW */
        'src/hello.legacy.js',
        'src/hello.amd.js',
        'src/hello.commonjs.js'
      }
    }
  }
```

**Comment by MrSwitch** [comment]
As you say this is important to help with your on going collaboration. i'll revisit the CommonJS way, as that would be closer to our common ideal structure and would be easy to switch over to Harmony anyway.

Is it alright if we close this for now?

**Comment by WebSeed** [comment]
No problem - this PR just moved all util methods to the same code block (top). I'm happy to close.

**Comment by MrSwitch** [comment]
Thanks

**Pull request closed without merging**
