### PR TITLE
More Google Drive support

### LINKED ISSUE #332: How to patch files for Google Drive?
I tried `hello('google').api("https://www.googleapis.com/drive/v2/files/" + fileId, 'patch', data)` and it doesn't work because the data is sent as FormData. It should be either in query string or in payload with `Content-Type: application/json`. 

API document: https://developers.google.com/drive/v2/reference/files/patch

### PR DESCRIPTION
**Pull request by xlc**
GET me/files/@{id}
PATCH me/files/@{id}

Fixes #332
Fixes logout failed to delete storage
Remove iframe that created by display:'none' option

### CODE REVIEW

**Comment by MrSwitch** [comment]
Awesome, i'll check it out next week - busy life.

**Comment by xlc** [comment]
There are also two other bug fixes in this PR. Please let me know if you should put those fixes into separate PRs.

**Comment by MrSwitch** [comment]
Hi, can you explain why set to null in `utils.store(name, null)`, rather than empty string?

**Comment by xlc** [comment]
It only delete the store if the value is null. Settings it to empty string will override the store value which somewhat delete the store.
https://github.com/KamiHQ/hello.js/blob/google-drive/dist/hello.all.js#L839

However, for chrome extension, it check `if (value)`, which evaluate to false for empty string, so the setter is not called.
https://github.com/KamiHQ/hello.js/blob/google-drive/dist/hello.all.js#L2922
It also check `if (value === null)`, so the delete is also not called for empty string.
https://github.com/KamiHQ/hello.js/blob/google-drive/dist/hello.all.js#L2929

**Comment by MrSwitch** [comment]
Hi @xlc can we break this PR up into the parts you identified?

Fixes #332
Fixes logout failed to delete storage
Remove iframe that created by display:'none' option - fixes #113 

Please also edit only the `src/` directory - the `dist/` is compiled along with tagged releases.

Thanks

**Comment by xlc** [comment]
New PRs #357 #358 #359

**Comment by MrSwitch** [comment]
Thanks alot!

**Pull request closed without merging**
