### PR TITLE
Fix for Google auth on Chrome apps

### PR DESCRIPTION
**Pull request by jordan-thoms**
After Chrome 47, launchWebAuthFlow no longer works with a
accounts.google.com URI, so we are unable to use it to auth with Google
( https://code.google.com/p/chromium/issues/detail?id=559523 )

This adds support code for a workaround where we redirect to a
redirect.html page hosted on the web, and from there use the
chrome.runtime APIs to communicate the auth response back to the
extension.

In order to use it developers will need to host the redirect.html file
with hello.js and set that as the redirect_url for hello.js, add the
chrome_ext_id option to their extension’s ID, and add an
‘externally_connectable’ option to their manifest to authorize their
site to send messages to their extension.

### CODE REVIEW

**Comment by MrSwitch** [comment]
I can't recreate this issue after reinstalling my Chrome Application and running...

> Version 47.0.2526.106 m
> Google Chrome is up to date.

Just to clarify is this a Chrome App or Browser Extension?

**Comment by xlc** [comment]
We found the issue in the extension

**Comment by MrSwitch** [comment]
I still can't recreate this problem, here' my demo working

image

**Comment by MrSwitch** [comment]
Have you got the right permissions?

https://github.com/MrSwitch/hellojs-chromeapp-demo/blob/db4a59ba8557a011edeb8b97e50fed66e1154f1f/manifest.json#L16

**Comment by xlc** [comment]
I am using Chrome Version 48.0.2564.79 beta (64-bit) on OSX 10.11.2 and the chrome app demo doesn't work for me.

**Comment by MrSwitch** [comment]
I'm closing this issue: Presumably a fix has since been applied to Chrome. There was no further comments in the link you shared above. So i dont know what to make of this. If you have any further insight please share.

Thanks for the feedback.

**Comment by mrajende** [comment]
Hi I am trying out the chrome extension, does the demo app work with as it is or do I need to create new chient ids?

**Pull request closed without merging**
